# Generated by Django 4.2.6 on 2023-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("serial_number", models.AutoField(primary_key=True, serialize=False)),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
